### ISSUE TITLE
Crash when starting playback from a playlist with only a single item

### ISSUE THREAD

**Issue by matgoebl** [aabaker/controldlna#13]
The MediaRouterPlayService crashes when the playlist contains only a single item and the playback is started:

```
FATAL EXCEPTION: main
Process: com.github.nutomic.controldlna, PID: 24026
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
       at java.util.ArrayList.get(ArrayList.java:413)
       at com.github.nutomic.controldlna.mediarouter.MediaRouterPlayService.resume(MediaRouterPlayService.java:338)
       at com.github.nutomic.controldlna.gui.RouteFragment.onClick(RouteFragment.java:486)
       at android.view.View.performClick(View.java:5612)
       at android.view.View$PerformClick.run(View.java:22288)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by aabaker** [comment]
The crash could happen in any scenario where tracks were added to a previously unused playlist and then a route was selected and the resume button was pressed.
