### ISSUE TITLE
Crash when opening the preferences

### ISSUE THREAD

**Issue by matgoebl** [aabaker/controldlna#17]
When opening the preferences, the application crashes.

Device: Moto G5, running Android 7.0

```
Shutting down VM
FATAL EXCEPTION: main
Process: com.github.nutomic.controldlna, PID: 28483
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.nutomic.controldlna/com.github.nutomic.controldlna.gui.PreferencesActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
       at com.github.nutomic.controldlna.gui.PreferencesActivity.onCreate(PreferencesActivity.java:70)
       at android.app.Activity.performCreate(Activity.java:6672)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
       ... 9 more

```

**Comment by aabaker** [comment]
I'm seeing this too - in fact it was getting in the way of me testing your other patches.

This code predates my involvement but the docs at https://developer.android.com/reference/android/support/v7/app/ActionBar.html#setDisplayHomeAsUpEnabled(boolean) suggest this function could be used to make the action bar close the prefs screen which sounds like sensible behaviour.

https://stackoverflow.com/questions/33597986/android-actionbar-always-null/33688760 indicates that getActionBar returning null is likely to be because the action bar hasn't been created properly which might also cause other issues. Looking at the preferences screen the action bar is indeed missing.

It appears that the "correct" fix is to switch from using a preference activity to preference fragments and ideally also to switch from the appcompat library to the jetpack library to handle version compatibility but that sounds like a lot of effort.

**Comment by matgoebl** [comment]
What is the consequence of not implementing it properly?
On Android 7 and Android 4 I still can use the classic back button, I see no problem there.
On newer Android it sounds like leaving the preferences closes the app. This is anoying, but how often does a user alter those few preference settings?
I would not spend the effort.
